sky:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        host: localhost
        port: 3306
        database: sky_take_out
        username: root
        password: 123456
    redis:
        host: 192.168.220.132
        port: 6379
        database: 0
    wechat:
        appid: wx1e0c2ce8981ea8a8
        secret: cf3b2110e0b500831c81e03b043b24e4